import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for the HappnCity website and app.",
};

const SECTIONS = [
  {
    title: "1. Who We Are",
    body: `This Privacy Policy explains how Modern Tech Creations ("HappnCity", "we", "us", "our") collects, uses, shares, and protects your personal data through this website and the HappnCity mobile app, in accordance with the Digital Personal Data Protection Act, 2023 ("DPDP Act") and other applicable Indian law. Modern Tech Creations acts as the "Data Fiduciary" for personal data processed through HappnCity.`,
  },
  {
    title: "2. Information We Collect",
    body: `On this website, we collect limited technical data (such as your approximate location, if you grant permission, used only to show events near you) and cookie/session data. On the HappnCity app, we additionally collect information you provide directly — such as your name, username, mobile number, email address, city, and user type — as well as information generated by your use of the platform, like the events you register for and organisations you join.`,
  },
  {
    title: "3. How We Use Your Information",
    body: `We use your information to operate and improve HappnCity, verify your identity via OTP, process event registrations and payments, send you relevant notifications, and communicate updates from organisations you follow or have registered with. We process personal data only for the purpose it was collected, and only with your consent where required under the DPDP Act.`,
  },
  {
    title: "4. Sharing Your Information",
    body: `Event organisers can see the registration details of attendees who register for their events (e.g. name, contact details, form responses). We may share data with service providers who help us operate HappnCity (such as hosting, payments, and SMS/OTP providers) under confidentiality obligations, or where required by law. We do not sell your personal information to third parties.`,
  },
  {
    title: "5. Payment Information",
    body: `Payments for paid events are processed by our third-party payment gateway providers. HappnCity does not store your full card, UPI, or bank account details.`,
  },
  {
    title: "6. Cookies & Location",
    body: `We use cookies and similar technologies to keep you signed in, remember your preferences (such as light/dark theme), and — with your permission — detect your approximate city to show relevant events. You can withdraw location permission at any time from your browser or device settings.`,
  },
  {
    title: "7. Data Retention",
    body: `We retain your personal data for as long as your account is active, or as needed to provide our services, comply with legal obligations, resolve disputes, and enforce our agreements.`,
  },
  {
    title: "8. Your Rights",
    body: `As a Data Principal under the DPDP Act, you have the right to access a summary of the personal data we hold about you, request correction or erasure of your data, withdraw consent at any time, and lodge a grievance with our Grievance Officer. You can exercise most of these rights directly from your account settings in the HappnCity app, or by contacting us.`,
  },
  {
    title: "9. Grievance Officer",
    body: `For any privacy-related questions, requests, or complaints, you may contact our Grievance Officer at moderntechcreations2025@gmail.com. We aim to acknowledge and resolve grievances promptly, in line with applicable law.`,
  },
  {
    title: "10. Data Security",
    body: `We take reasonable technical and organisational measures to protect your data, but no method of transmission or storage over the internet is completely secure.`,
  },
  {
    title: "11. Children's Data",
    body: `HappnCity is not intended for children under 13. If you are between 13 and 18, you may use HappnCity only with the consent and involvement of a parent or legal guardian, consistent with the DPDP Act.`,
  },
  {
    title: "12. Changes to This Policy",
    body: `We may update this Privacy Policy periodically. We will notify you of material changes through the app or this website.`,
  },
  {
    title: "13. Contact Us",
    body: `If you have questions about this Privacy Policy or how your data is handled, write to us at moderntechcreations2025@gmail.com.`,
  },
]

export default function PrivacyPolicyPage() {
  return (
    <article className="space-y-8">
      <div className="space-y-2">
        <h1 className="text-2xl font-bold text-foreground">Privacy Policy</h1>
        <p className="text-sm text-text-faint">Last updated: August 2026</p>
      </div>

      <div className="space-y-6">
        {SECTIONS.map((section) => (
          <section key={section.title} className="space-y-1.5">
            <h2 className="text-base font-semibold text-foreground">{section.title}</h2>
            <p className="text-sm leading-relaxed text-text-muted">{section.body}</p>
          </section>
        ))}
      </div>
    </article>
  )
}
